version: "3"
services:
  app:
    container_name: crud_mobile
    image: node:10.15.0-alpine
    build: .
    restart: always
    ports:
      - "3003:3003"
    tty: true
    volumes:
      - ./:/usr/app
    environment:
      - NODE_ENV=development
    command: "npx pm2 start ecosystem.config.js --no-daemon"